trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'Terraform'
    Contents:
      - 'Terraform/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
